######################################################################
# Automatically generated by qmake (2.01a) Tue May 27 23:00:43 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += small.cpp
