######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 2 14:58:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
