######################################################################
# Automatically generated by qmake (2.01a) Tue May 27 23:15:07 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += mlist.cpp
