######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 2 15:09:09 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
