######################################################################
# Automatically generated by qmake (2.01a) Tue May 27 23:10:06 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += szerelem.cpp
