######################################################################
# Automatically generated by qmake (2.01a) Tue May 27 23:04:50 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += file.cpp
