######################################################################
# Automatically generated by qmake (2.01a) Wed May 28 00:24:39 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += burning.h widget.h
SOURCES += burning.cpp main.cpp widget.cpp
